### PR TITLE
add config.py to .gitignore, create template files for slack_token.py and pdfcrowd_token.py

### PR DESCRIPTION
**Pull request by royrapoport**
Addressing @ax42 request in https://github.com/royrapoport/channelstats/issues/9

### CODE REVIEW

**Comment by jdq22** [comment]
Todo for this PR (I can get to this later today):
1. Rename config.py to config.py.template
2. Wipe out the values
3. Add comments specifying data type for each variable with example values.

**Comment by ax42** [comment]
Thanks.  We should add template files for slack_token.py and pdfcrowd_token.py - should I create a new issue?

**Comment by jdq22** [comment]
Please do @ax42!

**Comment by royrapoport** [comment]
Latest updates also address issue #11 and #12

**Review by jdq22 — APPROVED** [review]

**Pull request merged**
